### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by darrencauthon**
I switched from RSpec to Minitest just to cut some of the fat and to let you see how this stuff works in **Ruby** (versus RSpec way).

You can run the tests with this command:

```
ruby spec/apache_restart_spec.rb
```

These are just some basic suggestions, things I'd do if I were to hop into this codebase.  This will also give you an example as to how you can fake certain things in Ruby (which is the only way you'll be TDD'ing this stuff).

But like I mentioned on the user group, I think this is a very bad way to learn TDD.  I'd recommend going to http://cyber-dojo.org/ and starting with their examples.  Yes, they are contrived examples, but you have to get the testing fundamentals down before you can step up to the next levels.

### CODE REVIEW

**Comment by darrencauthon** [comment]
Just to be clear, this is not meant to be merged... just throwing out suggestions.

**Comment by rfreiberger** [comment]
@darrencauthon Awesome and thanks so much! I totally agree and will be focusing on Ruby core before I venture too far down the TDD path. Also I have read suggestions of Minitest for smaller projects, will start to give this a read. Again, thanks!

**Comment by darrencauthon** [comment]
It's no problem. 

Just for the record... Minitest and rspec are the same with regards to how they work for large Ruby projects. It's really more about the testing philosophy of the team as

**Comment by darrencauthon** [comment]
I'm closing this just to get it off my open list. But I'm keeping the code available for you to see. Cheers! :smile:

**Pull request closed without merging**
